### ISSUE TITLE
rechercher > remplacer ?

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#105]
@ROXBOZ tu as un moyen direct de rechercher et remplacer un mot comme sur indesign? ce serait utile pour vérifier que le mot "syndrome" soit toujours sans "^" sur le o. Let me know si ça existe sinon je changerai manuellement sur sanity 🎀

**Comment by ROXBOZ** [comment]
Coucou! Tu peux chercher en navigant sur le site (vercel) puis en changeant manuellement sur Sanity... mais non y'a pas de moyen de tout remplacer automatiquement
