### ISSUE TITLE
UI Links

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#107]
@ROXBOZ Dans les articles, il y a les liens vers le glossaire (bold + flèche), mais je pense que ce serait bien d'insérer d'autres liens. 
Ex: quand les auteurices recommandent d'écouter des podcasts érotiques, on pourrait mettre un 2e type de lien vraiment différent de ceux du glossaire et je propose de souligner + mettre en couleur? (je sais que les couleurs ne sont pas inclusives, mais il y a toujours le soulignement) et ça renvoie vers la page média? 

Ex avec commentaire dans le figma sur les 2 pages SOPK

**Comment by ROXBOZ** [comment]
@Anne-Soo Coucou, est-ce que tu pourrais définir tous les types de lien nécessaires et trouver le style pour repos et survol pour chacun stp?
Et on les met côte-àcôte et on s'assure que la différence est claire et que l'accessibilité est ok. Parce que ça m'a l'air de nouveau plein d'exceptions...

**Comment by ROXBOZ** [comment]
@Anne-Soo J'aime bien les liens ici
https://roudstudio.com/portfolio

**Comment by Anne-Soo** [comment]
@ROXBOZ 
Coucou! J'ai testé les différents besoin de lien:

- lien vers le glossaire : H3 Bold + flèche. Au suvol ou clic: devient violet (ou autre couleur) et la flèche s'anime
- lien vers d'autres ressources (comme recommander d'écouter des podcasts érotiques) + URL dans l'annuaire : H3 + soulignement. Au survol ou clic: devient violet + animation du filet (je trouvais cette référence simple et efficace : https://www.itsnicethat.com/news/gaza-resource-list-creative-industry-031123)
- titre des liens des articles ou autres références web dans les médias : H3 bold + soulignement. Au survol ou clic: changement de couleur

Je te mets les captures d'écran :)

PS: je peux pas gérer le filet du soulignement dans Figma, il faudrait que sur le site le soulignement soit un peu plus bas

**Comment by Anne-Soo** [comment]
<img width="1390" alt="Capture d’écran 2024-02-20 à 16 57 34" src="https://github.com/ROXBOZ/pvssy/assets/123372956/786160ef-b6d2-4969-89af-5d78421c52f0">



Glossaire + lien vers autres sources

**Comment by Anne-Soo** [comment]
<img width="1391" alt="Capture d’écran 2024-02-20 à 16 56 58" src="https://github.com/ROXBOZ/pvssy/assets/123372956/7d69c74b-896e-43aa-a5ac-9fb6b3792d5e">


URL des contenus web dans les médias

**Comment by Anne-Soo** [comment]
<img width="1386" alt="Capture d’écran 2024-02-20 à 17 02 31" src="https://github.com/ROXBOZ/pvssy/assets/123372956/90be1c9a-d743-4090-942c-1bb52a53e1b9">


site web de l'annuaire (le seul URL à intégrer dans l'annuaire)
