### ISSUE TITLE
Sanity > Annuaire

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#109]
@ROXBOZ serait-il possible de créer ces nouveaux tags pour les médias généraux/complets ? (On est d'accord qu'il est possible de sélectionner plusieurs tags à la fois non?)

- [ ] monde médical
- [ ] droit des patient·exs
- [ ] désir
- [ ] érotisme
- [ ] anatomie
- [ ] règles (ou menstruation, je sais pas encore ce qui est mieux)

**Comment by ROXBOZ** [comment]
Tu peux ajouter des tags directement dans Sanity
taper la première lettre pour voir si il existe déjà ou créer nouveau
