### ISSUE TITLE
UI Menu Map

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#114]

**Comment by ROXBOZ** [comment]
@Anne-Soo Hola!
Dans le menu, tu as maintenant ressources qui ouvre un encart avec des catégories couleurs... je te laisse designer cet encart comme tu veux - tout est permis ou presque.

Est-ce qu'on fait un burger menu et qu'on enlève tout le reste ? (trois petites bar qui s'ouvre) ou qu'on laisse le reste du menu pour avoir des accès directs?

**Comment by ROXBOZ** [comment]
Super nice et pratiquement près à l'emploi hahahaha avec les flèches en diagonale et les filets : https://www.dynergie.fr/

PAR OÙ COMMENCER > intro, guide, ...
DOULEURS > vaginisme, SOPK,...
RESSOURCES > annuaire, glossaire, ...
À PROPOS > No Dolor (à propos page actuelle), Devenir membre, faire un don

**Comment by Anne-Soo** [comment]
trop biiiiennnn! 
Hum, pour le menu burger, tu m'avais pas dit que c'était pas inclusif/adapté?

**Comment by Anne-Soo** [comment]
J'aime bien la référence que tu as envoyé, le site a de cool animations!

**Comment by ROXBOZ** [comment]
@Anne-Soo Trop bien. Non burger menu c'est ok, mais faut écrire menu à côté de l'icon c'est ça qui te rendait zinzin :)

**Comment by ROXBOZ** [comment]
@Anne-Soo Coucou! Alors comme dit sur whatsapp,  c'est maintenant plus ou moins fonctionnel, mais tu peux réfléchir au UI , couleurs, titrages, grille, on peut mettre d'autres éléments type les réseaux sociaux ou m'eme pour le menu douleur, directement des liens vers les ressources de ces douleurs pour montrer que c'est encastré... j'ai tenté un menu participer qui inclu devenir member et faire et don et ou on porrait rajouter les typeform pour médias et annuaire. 

e te laisse me faire un retour.

Ca marche que sur la homepage mais j'ai trop faim je fixe demain. Bisous!
