### ISSUE TITLE
UI boutons / tags / filtres

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#117]
Définir clairement les différents styles pour 

- [ ] Les boutons ACTION (ex: "recommander un spécialiste" sur la page annuaire) 
- [ ] Les boutons UI (ex: "en savoir plus" dans les exercices ou pour fermer un modal)
- [ ] Les filtres ("ex: vulve/vagin/utérus dans la rubrique douleur sur la home page)
- [ ] Les tags (non cliquables, dans l'annuaire...)

Il faut définir le style au repos et au survol pour les éléments cliquables. Les éléments non cliquables devrait être clairement non cliquable (peut être sans filet et avec un # .... 😭😭😭😭😭😭😭 #sans jugement # à l'écoute 😂😂😂😂😂😂😂😂  je laisse te démerder )

**Comment by Anne-Soo** [comment]
@ROXBOZ 

- Bouton **actions** sont des boutons qui font sortir de la page comme "recommander un pro" ou "partager un article" via les icones. Au repos, ce sont des boutons en rond ou aux angles arrondis en plein couleur pâle (peu utilisée dans le reste du site pour bien ressortir) avec texte foncé. Au survol ils changent de couleur (fond vert flash et texte violet foncé?) + **il y a une flèche quand c'est un bouton avec du texte comme *recommander un pro"** 
- **En savoir plus** (pour les exercices) : utilisons le + et le -. (sauf si ce n'est pas inclusif, à ce moment là j'ai une autre proposition, redis moi. Je trouvais juste que ça marchais bien en faisant des tests).
- **Filtres de pré-selection de la douleur** : Au repos = bouton aux angles arrondis avec filet + texte de la même couleur et pas de couleur de remplissage. Au survol: rien. Une fois selectionné: bouton avec remplissage et contour flouté orange (cf. idée de la douleur) + texte foncé 
- **tag** (médias) : Au repos = bouton aux angles arrondis avec filet + texte de la même couleur et pas de couleur de remplissage. Au survol: rien. Une fois sélectionné: bouton rempli avec la couleur du texte (donc violet très foncé) + texte blanc/crème
- Annuaire : les filtres douleur/région/type existent via des menus déroulants avec un remplissage de couleur. Cette même couleur est utlisée pour montrer les filtres sélectionnés à côté du nom de la soignante/du shop etc. Les filtres de recommandation des formulaires s'affichent avec une petite boule de couleur à côté (ça rappelle les boules de couleur des étapes des exercices + des points névralgiques, et surtout ça évite une surcharge et on comprend que ces filtres ne peuvent pas être cliquable ou sélectionnable sur cette page)

**Comment by Anne-Soo** [comment]
<img width="1391" alt="Capture d’écran 2024-02-16 à 20 01 21" src="https://github.com/ROXBOZ/pvssy/assets/123372956/ad9bfb64-0995-496e-944b-f60535117c58">

**Comment by Anne-Soo** [comment]
<img width="1392" alt="Capture d’écran 2024-02-16 à 13 53 40" src="https://github.com/ROXBOZ/pvssy/assets/123372956/8d901ac9-0ae7-4b67-879f-1e76c2dbb013">

**Comment by Anne-Soo** [comment]
<img width="1392" alt="Capture d’écran 2024-02-16 à 19 57 35" src="https://github.com/ROXBOZ/pvssy/assets/123372956/a9387e3b-2d7a-4434-bc0f-00ca74f3b4f7">

**Comment by ROXBOZ** [comment]
@Anne-Soo Coucou!

Quelques notes :
- il est impératif que le filtrage se fasse dans la colonne de gauche, sinon ça sert à rien d'avoir une colonne fixe.
- ce que j'ai fait jusqu'à présent utilise la même logique pour toutes les ressources (globales et par douleur),  tu propose un sytème complètement différent pour l'annuaire et les médias, pourquoi ? Ça me fait beaucoup de taf en plus et ça rend le truc plus difficile à maintenir...
- dans l'annuaire les filtres ressemblent aux tags et pourquoi il y a deux types de tags (gyneco/genève et recommendations)? 
- c'est quoi le filtre "type" dans annuaire ? - les professions des pros? là aussi j'ai l'impression qu'on s’était mis d'accord 🥲 Les entrées sont classés par catégories – donc si je choisis une douleur et une région, ça sert à rien de filtrer encore les spécialistes... il y aura trop de cas sans résultat. Et que faire du reste, shops, asso, etc ? C'est énormément de complications pour pas grand chose.

Les structures ontà nouveau beaucoup changé. J'ai l'impression qu'on repart dans ce truc de changer des structures sur lesquelles j'ai déjà beaucoup bossé, perso je pensais arriver au bout, éditer les couleurs (pleinf/filet/couleur) mais pas tout rechanger... 

Bref, mais parlons-en avec un café plus tard ;)

**Comment by Anne-Soo** [comment]
<img width="1393" alt="Capture d’écran 2024-02-19 à 19 51 13" src="https://github.com/ROXBOZ/pvssy/assets/123372956/f7de07da-e5af-476b-807f-8eae91a888f1">

**Comment by Anne-Soo** [comment]
@ROXBOZ je suis contente de cette page et j'ai réduit le nombre de couleurs et leur utilisation, il y en avait trop, là elles ont du sens et ça me semble plus équilibré :)

J'ai mis une flèche au bouton action, puisqu'on sort de cette page également. Je vais rajouter ce détail dans les règles posées plus haut

**Comment by Anne-Soo** [comment]
<img width="1395" alt="Capture d’écran 2024-02-20 à 12 05 01" src="https://github.com/ROXBOZ/pvssy/assets/123372956/ca41d130-a857-4855-b268-1763e969a7b2">

**Comment by Anne-Soo** [comment]
@ROXBOZ Détail important! 
Pour les alignements, surtout lorsqu'il y a des filets dans les titres de texte, il faut qu'il soit aligné au filet du sous-menu de gauche quand on arrive sur la page. Idem pour médias, glossaire etc.
+ le texte a plus de colonnes que le sous-menu :)

**Comment by ROXBOZ** [comment]
@Anne-Soo je propose de garder un filet tout autour de l'entrée annuaire, car les filets manquent cruellement de clareté.
