### ISSUE TITLE
Douleurs similaires

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#131]
En bas de l'article douleur, un composant qui lie vers d'autres douleur pour faciliter la navigation ?
Genre comme sur Zalando, t'as des produits similaires....

**Comment by Anne-Soo** [comment]
oui ça pourrait être bien. Ce serait cool d'avoir une proposition vers guide anatomique?

**Comment by ROXBOZ** [comment]
Du coup on peut dire les douleurs qui partagent le même filtre (utérus, mensutrations, etc. filtres de cartes sur la page d'accueil) + guide anatomique, noté!
