### ISSUE TITLE
tags medias

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#133]
@ROXBOZ coucou! tu serais ok d'ajouter ces tags en plus pour les medias dans sanity?
- désir
- éducation sexuelle
- érotique
- monde médical

**Comment by ROXBOZ** [comment]
yes, noté!

**Comment by ROXBOZ** [comment]
@Anne-Soo tu as maintenant la possibilité d'ajouter des tags au médias
