### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#144]
@ROXBOZ Il me semblait qu'on avait déjà un issue Header dans Github mais le trouve plus. 
Je te partage les captures d'écran avec le système du menu. Je l'ai ressimplifié depuis notre conversation de la dernière fois, et j'ai bien séparé "À propos" + "Nous soutenir" dans le header MAIS ils sont sur une même page avec systeme de sous-menu à gauche :

1. À propos (avec L'équipe + Comité scientifique)
2. Nous soutenir
3. Devenir membre

J'ai fait un test avec fond foncé + le menu centré qui fonctionne bien quand il y a moins de contenu dans le menu (ex: se soigner), dis-moi si ça te parle (à nouveau, les couleurs peuvent être changées etc., je parle du principe et de l'accessibilité)

**Comment by Anne-Soo** [comment]
<img width="1386" alt="Capture d’écran 2024-02-19 à 19 30 42" src="https://github.com/ROXBOZ/pvssy/assets/123372956/96bcbbb3-cedc-44a5-bc8b-e54f4d1657fa">

**Comment by Anne-Soo** [comment]
<img width="1398" alt="Capture d’écran 2024-02-19 à 19 30 53" src="https://github.com/ROXBOZ/pvssy/assets/123372956/8bc6dbc1-7da3-4edb-822e-0b93a4ae0621">

**Comment by ROXBOZ** [comment]
- [x] animation ouverture
- [x] onClick not onMouseEnter
- [x] logo pvssy quitte menu
- [x]  ajouter possibiliter de quitter le menu avec keyboard
- [ ] ANIMATION A L'OUVERTURE

**Comment by ROXBOZ** [comment]
@Anne-Soo coucou! J'ai bien avancé il y a encore pas mal de finesse à ajouter, j'y travaille. Il faudrait trouver une manière visuelle de démarquer les éléments cliquables des éléments non-cliquables (pour l'instant en mauve) au repos.

**Comment by ROXBOZ** [comment]
@Anne-Soo ce serait aussi pas mal de mettre tous les boutons vers des typeforms et les infos de contact dans le menu

**Comment by Anne-Soo** [comment]
<img width="1389" alt="Capture d’écran 2024-02-29 à 16 05 59" src="https://github.com/ROXBOZ/pvssy/assets/123372956/db5ed3f2-535c-4a6d-bbef-1ca532fd63d0">

@ROXBOZ coucou,
- je pense qu'il faut vraiment garder le texte de description ("des infos et des conseils pour mieux vivre son parcours de soin") dans la même taille que les suggestions (endométriose etc.)
- le fait que "intro" et "douleurs" soit en violet comme le menu selectionné "se soigner" pose un probleme de hierarchie/lisibilité. On pourrait mettre intro et douleur en opacité réduite ou en violet foncé du texte mais une nuance du dessous (si tu veux éviter l'opacité réduite)

**Comment by Anne-Soo** [comment]
<img width="1401" alt="Capture d’écran 2024-02-29 à 16 12 06" src="https://github.com/ROXBOZ/pvssy/assets/123372956/87a63d4e-57e9-403c-9a8a-0928ff7af1bc">

**Comment by Anne-Soo** [comment]
<img width="1392" alt="Capture d’écran 2024-02-29 à 16 48 33" src="https://github.com/ROXBOZ/pvssy/assets/123372956/5cbfeded-8758-410a-9e28-feb341c26d27">


@ROXBOZ Je préfère qu'on garde la même largeur de colonne pour "annuaire" et "exos"que lorsqu'il y en a 4 comme le sous menu "soigner" + essayer de l'aligner au niveau du menu. Histoire d'avoir une cohérence entre les éléments

**Comment by Anne-Soo** [comment]
<img width="1392" alt="Capture d’écran 2024-02-29 à 16 46 27" src="https://github.com/ROXBOZ/pvssy/assets/123372956/5830a7ef-d0e4-4e39-8b93-579e23473da6">

@ROXBOZ hésite pas à me dire ce que tu penses de ces 3 catégories sous l'appellation "nous soutenir", je trouve que ça fonctionne bien :)

**Comment by ROXBOZ** [comment]
Coucou @Anne-Soo ça fonctionne bien, mais ça rajoute un max de taf en plus car je dois créer des exceptions. Dans le premier menu, les pages sont listées sous un titre, ici elle apparaissent comme des ressources ... donc pour garder le tout éditable dans Sanity, c'est pas mal de boulot. Peut-on garder ce genre de détails pour la fin ? <3

**Comment by ROXBOZ** [comment]
@Anne-Soo Coucou! Pour l’histoire de l'alignement avec le menu, c'est de nouveau ton print mindset qui parle. Il faut penser au responsive + si on force l'alignement il y aura des énormes espaces sur certains écran... ou il y aura un énorme espace sur la gauche... On peut en parler la prochaine fois!

**Comment by Anne-Soo** [comment]
<img width="574" alt="Capture d’écran 2024-03-13 à 10 18 44" src="https://github.com/ROXBOZ/pvssy/assets/123372956/a6ccdc77-76d6-43b2-894b-f36865466595">

**Comment by Anne-Soo** [comment]
@ROXBOZ Coucou, voici le visuel pour le responsive, j'hésite effectivement à rajouter les liens vers les réseaux sociaux. À tester

**Comment by Anne-Soo** [comment]
<img width="576" alt="Capture d’écran 2024-03-13 à 10 17 31" src="https://github.com/ROXBOZ/pvssy/assets/123372956/6d330cac-e5c0-446e-9300-953599404d08">

**Comment by Anne-Soo** [comment]
@ROXBOZ j'hésite à ajouter le "nous soutenir" en bouton call to action, hésite pas à me dire ce que tu en penses :)
