### ISSUE TITLE
Header Mobile

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#153]
@Anne-Soo Coucou, il faudrait imaginer le menu pour mobile, ça demande plus qu'une adaptation responsive de base. 

![Image](https://github.com/ROXBOZ/pvssy/assets/79715224/dc831d75-bf1c-4061-889b-29694803624a)

**Comment by Anne-Soo** [comment]
@ROXBOZ coucou! J'avais mis dans l'issu Header générale. Je te remets ici le visuel, j'hésitais à mettre "nous soutenir" sous forme de bouton call to action. Let me know ce que tu en penses :)

**Comment by Anne-Soo** [comment]
<img width="574" alt="Capture d’écran 2024-03-13 à 10 18 44" src="https://github.com/ROXBOZ/pvssy/assets/123372956/010cd6a0-75d1-47e0-b015-edcdc6db235c">

**Comment by Anne-Soo** [comment]
<img width="576" alt="Capture d’écran 2024-03-13 à 10 17 31" src="https://github.com/ROXBOZ/pvssy/assets/123372956/0e28049d-63b5-4063-8738-193f1838fe56">
