### ISSUE TITLE
COSMÉTIQUE

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#168]
Coucou!
Je compile ici les différentes corrections cosmétiques qui me semblent importantes 💚

**Comment by Anne-Soo** [comment]
<img width="353" alt="Capture d’écran 2024-03-19 à 14 55 38" src="https://github.com/ROXBOZ/pvssy/assets/123372956/55f108d9-f7c1-44dd-bff6-ed3e342a1596">


La taille des picto est bonne, mais la couleur foncée les met en haut de la hierarchie. 
À mettre dans la couleur de l'autre bouton approche > mauve

**Comment by Anne-Soo** [comment]
<img width="1439" alt="Capture d’écran 2024-03-19 à 14 58 15" src="https://github.com/ROXBOZ/pvssy/assets/123372956/bdbfa6b9-1aaf-4878-b2f2-1e895579da3f">

<img width="1394" alt="Capture d’écran 2024-03-19 à 15 00 41" src="https://github.com/ROXBOZ/pvssy/assets/123372956/bd58a554-3849-479f-9722-dda72385dcb7">



Séparer le texte de l'image: rapprocher Medsexplain/Noemie du titre + mettre plus d'espace entre ce bloc de texte et l'image, comme sur l'exemple (image 2)

**Comment by Anne-Soo** [comment]
<img width="822" alt="Capture d’écran 2024-03-19 à 15 03 15" src="https://github.com/ROXBOZ/pvssy/assets/123372956/fb9366ad-6199-4865-8224-aed830be5af2">


<img width="1353" alt="Capture d’écran 2024-03-19 à 15 03 27" src="https://github.com/ROXBOZ/pvssy/assets/123372956/c2fb09af-1b6d-40c8-aba1-bfce9055397e">

Note générale: je préfère que les angles des images soient arrondis comme dans ces exemples figma mais pas plus. les formes dans les illu sont déjà molles et souples, ça ne leur rend pas trop service d'avoir des contours d'images trop ronds

**Comment by Anne-Soo** [comment]
<img width="1416" alt="Capture d’écran 2024-03-19 à 15 07 41" src="https://github.com/ROXBOZ/pvssy/assets/123372956/2df6cdc1-cbda-47e1-8134-6c1e26175937">
<img width="1407" alt="Capture d’écran 2024-03-19 à 15 11 15" src="https://github.com/ROXBOZ/pvssy/assets/123372956/92e45a43-9d11-4da1-9266-ad3d2482a771">





Je te mets ici les corrections des tailles pour davantage de cohérence entre les éléments
Est-ce qu'il est possible de garder la grille de 4 colonnes dans le menu pour exercices/annuaire? ça serait plus cohérent aussi, là les colonnes sont super larges, n'ayons pas peur du vide

**Comment by ROXBOZ** [comment]
coucou je clos celui-ci car j'ai tout fait et je te laisse me récrire des tiquets séparés pour les prochains c'est plus facile à gérer :)
