### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#182]
coucou, je te mets ici les bugs que j'ai trouvé:

<img width="1348" alt="Capture d’écran 2024-05-08 à 16 52 39" src="https://github.com/ROXBOZ/pvssy/assets/123372956/27db874b-4ba8-4fcd-8373-3204cc666cf3">

**Comment by Anne-Soo** [comment]
<img width="1043" alt="Capture d’écran 2024-05-08 à 17 01 15" src="https://github.com/ROXBOZ/pvssy/assets/123372956/311dcc40-ce4b-41a9-9213-4c371547fbe4">

**Comment by Anne-Soo** [comment]
Hyper chelou, dans sanity c'est écrit normalement, mais publié sur vercel, il y a un soucis d'espace avant et après le slash au niveau du titre plaisir/anti douleur


<img width="1439" alt="Capture d’écran 2024-05-09 à 21 53 40" src="https://github.com/ROXBOZ/pvssy/assets/123372956/49ba4ce8-7379-4110-b7a1-05da8d859efd">

**Comment by Anne-Soo** [comment]
Il y a des mots reliés au glossaire dans sanity qui n'apparaissent pas dans le texte publié. 
Comme ici "dilatateurs vaginaux" dans vaginisme>que puis-je faire solo?


<img width="1346" alt="Capture d’écran 2024-05-09 à 21 59 58" src="https://github.com/ROXBOZ/pvssy/assets/123372956/1f6d1b4c-69d0-40f3-bc3b-406677f1186e">

<img width="1349" alt="Capture d’écran 2024-05-09 à 21 57 50" src="https://github.com/ROXBOZ/pvssy/assets/123372956/168b529c-1629-4799-92b8-d5f4aa147605">

**Comment by Anne-Soo** [comment]
Dans les exercices, les points/puces n'apparaissent pas alors que j'en ai mis dans sanity. 
Du coup quand il y a beaucoup de texte (comme là pour un exercice dans vaginisme), c'est pas super lisible. Pareil, je ne sais pas pourquoi ça ne les affiche pas...


<img width="1430" alt="Capture d’écran 2024-05-09 à 21 55 21" src="https://github.com/ROXBOZ/pvssy/assets/123372956/140b8540-4e06-4168-8334-e6357da37af3">

**Comment by Anne-Soo** [comment]
Là si je veux sortir du menu et cliquer en bas sur la page où je suis actuellement, je ne peux pas, le menu en accordéon reste coincé. Je suis obligée de cliquer sur un lien et changer de page pour que le menu disparaisse

<img width="1409" alt="Capture d’écran 2024-05-09 à 22 04 33" src="https://github.com/ROXBOZ/pvssy/assets/123372956/c9fe6230-415a-4970-9aa9-7e9bae7a2579">

**Comment by Anne-Soo** [comment]
2e bug du menu en accordéon: on ne peut pas scroller pour atteindre l'article vulvodynie!

<img width="1389" alt="Capture d’écran 2024-05-09 à 22 24 22" src="https://github.com/ROXBOZ/pvssy/assets/123372956/4ab61515-6cf6-45a9-be23-719cd106f060">

**Comment by Anne-Soo** [comment]
J'ai mis à jour le lien de Fiona Bourdon, mais le texte ne se remet pas en bold.

<img width="643" alt="Capture d’écran 2024-05-10 à 17 39 09" src="https://github.com/ROXBOZ/pvssy/assets/123372956/78dde03a-c07d-4441-a171-f2954254a96b">

**Comment by Anne-Soo** [comment]
La taille des illus est petite (alors que c'est ok sur mon png) + il faudrait mettre plus de marge dans le cadre pour la légende je pense

<img width="1023" alt="Capture d’écran 2024-05-10 à 15 46 49" src="https://github.com/ROXBOZ/pvssy/assets/123372956/f5250c59-ea80-4c58-8b59-bc5700044fb2">

**Comment by Anne-Soo** [comment]
Probleme d'affichage des images sur Safari

<img width="1440" alt="Capture d’écran 2024-05-11 à 14 35 26" src="https://github.com/ROXBOZ/pvssy/assets/123372956/807713e9-5545-4bba-99c6-dc97a49b5626">

**Comment by ROXBOZ** [comment]
> Il y a des mots reliés au glossaire dans sanity qui n'apparaissent pas dans le texte publié. Comme ici "dilatateurs vaginaux" dans vaginisme>que puis-je faire solo?
> 
> <img alt="Capture d’écran 2024-05-09 à 21 59 58" width="1346" src="https://private-user-images.githubusercontent.com/123372956/329371274-1f6d1b4c-69d0-40f3-bc3b-406677f1186e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii8xMjMzNzI5NTYvMzI5MzcxMjc0LTFmNmQxYjRjLTY5ZDAtNDBmMy1iYzNiLTQwNjY3N2YxMTg2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMDM2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjA3YmQ0NGE5NGYzZWI4NWRiNmU0ZDczYjM4ZGEyZDUyZDY3YjMwNmU1MTUxMDhiNzM4MzQ4OGVhYzQ4OWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nadmMyIZWrtpDDFiXupovL256ShbDDVXAmsIe4wIWvU"> <img alt="Capture d’écran 2024-05-09 à 21 57 50" width="1349" src="https://private-user-images.githubusercontent.com/123372956/329370744-168b529c-1629-4799-92b8-d5f4aa147605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii8xMjMzNzI5NTYvMzI5MzcwNzQ0LTE2OGI1MjljLTE2MjktNDc5OS05MmI4LWQ1ZjRhYTE0NzYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMDM2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2MxYzEwZGExNTY2N2NlYmVmNjhhOTZhYTIzY2JhNTJiOGM5NTBmMTZlNGUwYTYyNDM4NDJhNjZjMzUyYmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gUeFMIF5m5zrtE9TXWApk_f03gd9prdWKVhvKw0VP-Q">

On a fait comme ça selon demande : il faut attribuer la douleur concernée au terme dans Sanity pour que le terme apparaissent dans le glossaire de la douleur concernée (donc possibilité d'ajouter des termes au glossaire qui ne figurent pas dans le texte) et surligner les mots dans les paragraphes pour les liés à un terme (possibilité de gérer les répétitions et de lier des synonymes)
