### ISSUE TITLE
Homepage : animation point orange

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#66]
point névralgique animé orange en fil conducteur:

- [x] - fond tagline
- [x] - data
- [x] - tags douleurs 
- [x] autres tags dans les pages ressources
- [x] - pré-selection des cartes/articles
- [x] - changement de couleur du bouton newsletter (footer)

Changement de couleur de texte lors des pré-selections:

- [x] - footer (infos côté droit)

**Comment by ROXBOZ** [comment]
@Anne-Soo tu veux dire quoi par data  et comment est-ce que tu veux changer les cartes au survol ? J'ai déjà fait les tags douleurs animé sur la page d’accueil je pense que si les cartes réagissent la m'eme chose, ça va faire too much?

**Comment by Anne-Soo** [comment]
@ROXBOZ 

data = les ronds de couleur, le fameux 1 personne à vulve sur 10

je vois ce que tu veux dire pour les cartes. Il faudrait quand meme une animation (différente de l'actuelle), je vais chercher une reference que j'aime bien

**Comment by ROXBOZ** [comment]
@Anne-Soo J'ai fait l’animation data... ça me fait penser à un magasin des année 80 qui s'appelait ABM... dis moi ce que tu en penses! 
Du coup ça fera vraiment trop avec les cartes, mais je suis d’accord qu'elles ont besoin de changer...

https://augrandpassage.blogspot.com/2008/07/abm-et-epa-ou-comment-migros-et-coop-se.html

**Comment by Anne-Soo** [comment]
Haha, c'est vrai mais ça me semble bien :)
C'est juste que tout est trop gros, les titres comme le texte comme l'image, donc c'est un peu lourd et flashy, on pourra regarder pour apporter davantage de contraste
