### ISSUE TITLE
Marquee

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#71]
@Anne-Soo  : Concernant la bannière verte, je sais pas ce que tu en penses mais quand on arrive sur le site, on devrait la voir en bas sans avoir à scroller. Qu’en penses-tu?

Aussi : ces bannières qui défilent, ça s'appelle des marquees, c'est de la MERDE à faire parce qu'il faut bidouiller pour donner l'impression que c'est en loop, entre la vitesse et la longueur du texte (Si tu changes le texte, il faut le répéter plusieurs fois et bidouiller avec la vitesse pour que ça fasse comme on aime). Bref, j'ai constaté avec le temps que ça marche bien avec des messages courts, genre SALE SALE SALE ou un truc du genre :’) Et si on ne l’animait pas mais qu'on mettait un bouton radiant dessus pour le typeform???? C'est aussi con que c'est pas très accessible d'avoir un lien qu'il faut choper au passage comme à la pêche au canards...

**Comment by Anne-Soo** [comment]
@ROXBOZ je vois bien ce que tu veux dire j'y reflechissais hier en faisant le typeform...
Du coup on laisse juste le bouton qui donne accès au typeform et sinon on retrouve la proposition de recommander dans la home page>nous soutenir

**Comment by ROXBOZ** [comment]
@Anne-Soo Hola! Alors, oui, le "marquee" – je propose la solution suivant : pas d'animation, pas de pêche aux canards. 
Il est remonté sur l'écran d'accueil, donc on le voit avant de commencer à scroller. Il y a déjà l'animation de la douleur au dessus, donc une animation à la fois, c'est bon. Le bouton n'est pas "animé douleur" car ça fait trop avec l'animation en dessus.

Tu peux changer la tagline, le marquee et l'intro via SANITY, youpi! Le reste viendra à mesure....
