### ISSUE TITLE
Écriture inclusive

### ISSUE THREAD

**Issue by Anne-Soo** [ROXBOZ/pvssy#72]
@ROXBOZ 

Juste pour qu'on soit en accord sur l'écriture inclusive (je sais plus où on en est entre l'ancienne version et le travail que tu as fait depuis sur les textes) : le x est toujours au milieu, avant le s.

donc c'est : concerné·exs, informé·exs, soignant·exs etc.

**Comment by ROXBOZ** [comment]
@Anne-Soo : noté! si jamais pour rappel, cette solution n'est PAS accessible à défaut d'être inclusive donc à utiliser en dernier recours et si possible utiliser une forme épicène de type "les spécialistes"

**Comment by Anne-Soo** [comment]
oui! J'essaye de faire attention :)
