### ISSUE TITLE
Créer encart à propos homepage

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#73]

**Comment by ROXBOZ** [comment]
@Anne-Soo Je te laisse découvrir dans Sanity, tu peux créer un encart et choisir la couleur entre violet et vert

**Comment by Anne-Soo** [comment]
<img width="1432" alt="Capture d’écran 2024-01-23 à 13 15 22" src="https://github.com/ROXBOZ/pvssy/assets/123372956/83b84d35-b508-496b-84b5-18c3cc352d15">

J'ai regardé à différents moments de la journée mais l'encart ne s'affiche pas, donc je vois pas mes modifications

**Comment by ROXBOZ** [comment]
@Anne-Soo  dsl pour le manque de clarté, je disais de regarder dans sanity comment se présente la gestion du composant car je n'avais pas encore monté le truc sur le site... d'ou la présentation fuchsia chelou. maintenant c'est tout bon des deux cotés
