### ISSUE TITLE
NavBlock Nav > permettre la nav de prendre les ressources

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#75]
Les diverses navigations ne sont pas encore éditables via Sanity. @Anne-Soo Merci de valider puis je ferais le nécessaire pour que les navigation SelfCare et SelfLearning soient éditables via l’onglets Menus de Sanity

**Comment by Anne-Soo** [comment]
@ROXBOZ hum, comment s'appelle l'onglet que je dois valider dans sanity?
