### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#85]

**Comment by ROXBOZ** [comment]
- [ ] home page
- [x] menu
- [x] footer
- [x] articles douleurs
- [x] pages
- [x] annuaire douleur
- [x] annuaire
- [x] glossaire douleur
- [x] glossaire
- [x] médias douleur 
- [x] médias 
- [x] exercices douleurs
- [x] exercices

**Comment by ROXBOZ** [comment]
Corrections Rox

- [x] Bouton "participer" dans menu mobile
- [x] clignotement quand page sélectionnée mobile -> réglé en désactivant page transition
- [x] mobile menu ne ferme pas tjs après sélection -> réglé en désactivant page transition
- [x] pour commencer dans breadcrumbs > page d'accueil 
- [x] mobile > Ressources douleurs menu après contenu
- [x] médias complets > problème responsive menu
- [x] titre ressource glossaire apparait par dessus menu -> s'est fixé tt seul ?
- [x] titre annuaire glossaire apparait par dessus menu -> s'est fixé tt seul ?
- [x] À propos bug depuis menu
- [x] responsive 404
- [x] alignements menu ouvet/fermé/main sur mobile
- [x] menu parfois disparait
- [x] médical/sexo devant menu

Corrections @Anne-Soo 

- [ ] Mettre des espaces insécables devant les ":" (ou pas d'espace du tout c'est une différence typographique entre la France et la Suisse romande si jamais

**Comment by Anne-Soo** [comment]
@ROXBOZ coucou! Si jamais il me semblait que tu m'avais dit que tu faisais la micro typo avec un système automatisé donc je n'ai effectivement rien fait à ce niveau là. Je vais regarder comment faire de la micro typo via sanity, ce ne sont pas les mêmes raccourcis que sur indesign

**Comment by ROXBOZ** [comment]
@Anne-Soo ??? euh je crois pas avoir dit ça, on a du mal se comprendre... pour ce qui est capitalisé / en minuscule, oui, mais pas pour les espaces insécables

@Anne-Soo pour Sanity, c'est comme dans Word, c’est **option+space**
