### ISSUE TITLE
Idée : Créer une page "Participer" ???

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#92]
On pourrait créer une page "Participer" ou on expliquerait que les utilisateurices sont encouragéexs à nous écrire, à témoigner, à partager des infos, blabla. Avec des liens vers les typeforms pour l'annuaire, les médias et l'agenda.

Ensuite dans le menu du header, au lieu du bouton "je recommande un spécialiste" on aurait "je participe" – et dans le marquee (la bannière verte) on reste sur l'annuaire qui est la priorité.

**Comment by ROXBOZ** [comment]
On devrait aussi y mentionner les liens vers "devenir membre" et "faire un don" et sur les pages "devenir membre" et "faire un don" on rajouterait une phrase > contribuer autrement > qui link à la page participer et voilà la boucle est bouclée

**Comment by Anne-Soo** [comment]
@ROXBOZ bonne idée, je vois où tu veux en venir, je me demandais comment gérer le donner/devenir membre et motiver à témoigner... je regarde demain, je termine sur les articles aujourd'hui

**Comment by ROXBOZ** [comment]
@Anne-Soo du coup plutôt qu'une page, je pense qu'il faut plutôt ajouter dans le menu  ou on peut mettre les page devenir membre et faire un don, les typeformes ....
