### ISSUE TITLE
Les vieilles cartes

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#93]
Je sais pas toi, mais je trouve que cette grille de cartes douleurs est un peu molle... comme si elle était trop timide... et si on faisait des cartes pleine largeur un peu comme le site en italien que tu as partagé l'autre jour ou l'encart "à propos" ??? Grande image d'un côté, et de l'autre le nom et d'autes infos (genre symptomes) pour aider l'utilsateurice à sélectionner...

pleine largeur, mais pas trop haute pour qu'on voit quand on filtre

**Comment by Anne-Soo** [comment]
@ROXBOZ Je garde en tête ce que tu dis. J'avance sur l'annuaire et les articles, on revient sur la homepage à la fin? (pas pour le fonctionnement, je parle du cosmétique)

**Comment by ROXBOZ** [comment]
@Anne-Soo voilà, tu me diras ce que tu en penses 👯
