### ISSUE TITLE
typeform annuaire > intro ?

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#95]
@Anne-Soo > Est-ce que c'est possible d'ajouter une intro au typeform ? parce que si tu cliques sur "je recommande" t'arrives directement dans le vif du sujet mais je trouve que ce serait bien d'avoir une intro qui explique ce qu'on cherche etc. et que tonton René qui est dentiste n'a pas sa place ici?

**Comment by Anne-Soo** [comment]
@ROXBOZ  c'est fait! Hésite pas si tu penses que j'ai oublié d'autres infos qui te semblent importantes.

**Comment by Anne-Soo** [comment]
Tonton René hehe
