### ISSUE TITLE
Rebond plus fine ?

### ISSUE THREAD

**Issue by ROXBOZ** [ROXBOZ/pvssy#97]
@Anne-Soo Coucou! je sais pas ce que tu en penses mais je trouve que maintenant qu'on utilise la Rebond beaucoup plus qu'avant, semibold est trop bold... tu ne trouves pas ? genre j'ai pas changé la taille des textes mais tout est devenu trop lourd. Est-ce que tu as la Rebond en medium ? j'aimerais essayer :)

**Comment by Anne-Soo** [comment]
@ROXBOZ Je suis d'accord, je me posais  la question. Je pense qu'il faudrait revoir les tailles, tout est trop gros. Dis moi si tu préfères qu'on voit les tailles ensemble via un zoom ou si je change ça dans le figma et tu ajustes. On verra si la rebond est toujours trop bold à ce moment là.
